accessing
stringDatesAndInfo
	<script: 'self stringDatesAndInfo inspect'>
	"A collection of dates with additional information."
	^ #(
	"2015" "extra info"
	'29-Jan-2015' 'Pharo Days 2015 29-30 Jan'
	'3-Apr-2015' ''
	'17-Apr-2015' 'Pharo 4.0 Released'
	'22-May-2015' ''
	'5-June-2015' 'Moose 5.1 Released'
	'10-Jun-2015' 'Includes report'
	'13-Jul-2015' 'ESUG Italy 13-17 July 2015'
	'11-Sept-2015' ''
	'23-Oct-2015' 'First time in DCC Chile'
	'27-Nov-2015' ''
	'18-Dec-2015' 'CI did not worked'
	
	"2016"
	'29-Jan-2016' 'Only Juraj in Chile'
	'26-Feb-2016' 'No in Chile'
	'31-Mar-2016' 'Pharo Days 2016 March 31 - April 1'
	'29-Apr-2016' ''
	'12-May-2016' 'Pharo 5.0 Released'
	'27-May-2016' ''
	'29-Jun-2016' 'Not announced?'
	'29-Jul-2016' 'Was announced but did not happen in Lille, only in Chile'
	'15-Aug-2016' 'Moose 6.0 Released'
	'22-Aug-2016' 'ESUG 22-26 August 2016 Czech Republic'
	'30-Sep-2016' 'If I remember well it was not organized in the end in Lille. Not in Chile.'
	'4-Nov-2016'  'Not in Chile'
	'25-Nov-2016' 'Not in Chile'
	'16-Dec-2016' 'Not in Chile. Christmas Party in Lille.'
	
	"2017"
	'27-Jan-2017' 'Not in Chile. Huge automatic changes of openned issues.'
	'3-March-2017' 'A lot of conversation on Slack'
	)